version: '3'
services:
  autoheal:
    deploy:
      replicas: 1
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
  bot:
    image: mikedevita/onairdiscordbot:latest
    container_name: onairdiscordbot
    labels:
      autoheal: true
    # use external .env file
    env_file: .env
    # or pass environment variables directly in by defining them like so. (Make sure toe remove the env_file line above.)
    # environment:
      # ONAIR_COMPANYID: ${ONAIR_COMPANYID}
      # ONAIR_VAID: ${ONAIR_VAID}
      # ONAIR_APIKEY: ${ONAIR_APIKEY}
      # ONAIR_OPERATION_MODE: ${ONAIR_OPERATION_MODE}
      # DISCORD_TOKEN: ${DISCORD_TOKEN}
      # DISCORD_CLIENTID: ${DISCORD_CLIENTID}
      # DISCORD_GUILDID: ${DISCORD_GUILDID}
      # DISCORD_OWNERID: ${DISCORD_OWNERID}
      # DISCORD_ONCONNECT_NOTICE_CHANNELID: ${DISCORD_ONCONNECT_NOTICE_CHANNELID}
      # DISCORD_ONCONNECT_NOTICE_ENABLED: ${DISCORD_ONCONNECT_NOTICE_ENABLED}
      # DISCORD_ONCONNECT_NOTICE_AUTODELETE: ${DISCORD_ONCONNECT_NOTICE_AUTODELETE}
      # DISCORD_ONCONNECT_NOTICE_AUTODELETE_DELAY_MS: ${DISCORD_ONCONNECT_NOTICE_AUTODELETE_DELAY_MS}
      # DISCORD_FLEET_STATUS_CHANNELID: ${DISCORD_FLEET_STATUS_CHANNELID}
      # DISCORD_FLIGHTS_STATUS_CHANNELID: ${DISCORD_FLIGHTS_STATUS_CHANNELID}
      # DISCORD_FBOS_STATUS_CHANNELID: ${DISCORD_FBOS_STATUS_CHANNELID}
      # DISCORD_MEMBERS_STATUS_CHANNELID: ${DISCORD_MEMBERS_STATUS_CHANNELID}
      # DISCORD_FLEET_STATUS_ENABLED: ${DISCORD_FLEET_STATUS_ENABLED}
      # DISCORD_FLEET_STATUS_INTERVAL: ${DISCORD_FLEET_STATUS_INTERVAL}
      # DISCORD_FLEET_STATUS_SORTCOLUMN: ${DISCORD_FLEET_STATUS_SORTCOLUMN}
      # DISCORD_FLEET_STATUS_PAGESIZE: ${DISCORD_FLEET_STATUS_PAGESIZE}
      # DISCORD_FLIGHTS_STATUS_ENABLED: ${DISCORD_FLIGHTS_STATUS_ENABLED}
      # DISCORD_FLIGHTS_STATUS_INTERVAL: ${DISCORD_FLIGHTS_STATUS_INTERVAL}
      # DISCORD_FLIGHTS_STATUS_SORTCOLUMN: ${DISCORD_FLIGHTS_STATUS_SORTCOLUMN}
      # DISCORD_FLIGHTS_STATUS_PAGESIZE: ${DISCORD_FLIGHTS_STATUS_PAGESIZE}
      # DISCORD_FBOS_STATUS_ENABLED: ${DISCORD_FBOS_STATUS_ENABLED}
      # DISCORD_FBOS_STATUS_INTERVAL: ${DISCORD_FBOS_STATUS_INTERVAL}
      # DISCORD_FBOS_STATUS_SORTCOLUMN: ${DISCORD_FBOS_STATUS_SORTCOLUMN}
      # DISCORD_FBOS_STATUS_PAGESIZE: ${DISCORD_FBOS_STATUS_PAGESIZE}
      # DISCORD_MEMBERS_STATUS_ENABLED: ${DISCORD_MEMBERS_STATUS_ENABLED}
      # DISCORD_MEMBERS_STATUS_INTERVAL: ${DISCORD_MEMBERS_STATUS_INTERVAL}
      # DISCORD_MEMBERS_STATUS_SORTCOLUMN: ${DISCORD_MEMBERS_STATUS_SORTCOLUMN}
      # DISCORD_MEMBERS_STATUS_PAGESIZE: ${DISCORD_MEMBERS_STATUS_PAGESIZE}
      # DISCORD_ONCONNECTNOTICE: ${DISCORD_ONCONNECTNOTICE}
      # DISCORD_DEPLOYCOMMANDS: ${DISCORD_DEPLOYCOMMANDS}
      # DISCORD_ONAIR_SLASH_CMNDS_ENABLED: ${DISCORD_ONAIR_SLASH_CMNDS_ENABLED}
      # DISCORD_DETAIL_STATUS_ENABLED: ${DISCORD_DETAIL_STATUS_ENABLED}
      # DISCORD_DETAIL_STATUS_INTERVAL: ${DISCORD_DETAIL_STATUS_INTERVAL}
      # DISCORD_DETAIL_STATUS_CHANNELID: ${DISCORD_DETAIL_STATUS_CHANNELID}
      # LOG_LEVEL: ${LOG_LEVEL}