FROM node:18-alpine
WORKDIR /app

ARG DISCORD_TOKEN
ARG DISCORD_CLIENTID
ARG DISCORD_GUILDID
ARG DISCORD_OWNER
ARG DISCORD_CHANNEL
ARG DISCORD_ONCONNECTNOTICE
ARG DISCORD_DEPLOYCOMMANDS
ARG ONAIR_COMPANYID
ARG ONAIR_VAID
ARG ONAIR_APIKEY
ARG LOGLEVEL

ENV DISCORD_TOKEN $DISCORD_TOKEN
ENV DISCORD_CLIENTID $DISCORD_CLIENTID
ENV DISCORD_GUILDID $DISCORD_GUILDID
ENV DISCORD_OWNER $DISCORD_OWNER
ENV DISCORD_CHANNEL $DISCORD_CHANNEL
ENV DISCORD_ONCONNECTNOTICE $DISCORD_ONCONNECTNOTICE
ENV DISCORD_DEPLOYCOMMANDS $DISCORD_DEPLOYCOMMANDS
ENV ONAIR_COMPANYID $ONAIR_COMPANYID
ENV ONAIR_VAID $ONAIR_VAID
ENV ONAIR_APIKEY $ONAIR_APIKEY
ENV LOGLEVEL $LOGLEVEL

COPY package.json /app
COPY . /app
RUN rm /app/.env
RUN cd /app
RUN npm install && npm install typescript tsc ts-node -g

CMD ["npm", "start"]