export type TranslatedAirport = {
    Id:                                 string 
    ICAO:                               string 
    IATA?:                               string
    DisplayName:                        string
    HasNoRunways?:                       boolean
    TimeOffsetInSec?:                    number
    LocalTimeOpenInHoursSinceMidnight?:  number
    LocalTimeCloseInHoursSinceMidnight?: number
    Name:                               string
    State?:                              string
    CountryCode?:                        string
    CountryName?:                        string
    City?:                               string
    Latitude?:                           number
    Longitude?:                          number
    Elevation?:                          number
    HasLandRunway?:                      boolean
    HasWaterRunway?:                     boolean
    HasHelipad?:                         boolean
    Size:                               number 
    TransitionAltitude?:                 number
    LastMETARDate?:                      Date
    IsNotInVanillaFSX?:                  boolean
    IsNotInVanillaP3D?:                  boolean
    IsNotInVanillaXPLANE?:               boolean
    IsNotInVanillaFS2020?:               boolean
    IsClosed?:                           boolean
    IsValid?:                            boolean
    MagVar?:                             number
    IsAddon?:                            boolean
    RandomSeed?:                         number
    LastRandomSeedGeneration?:           Date
    IsMilitary?:                         boolean
    HasLights?:                          boolean
    AirportSource:                      number
    LastVeryShortRequestDate?:           Date
    LastSmallTripRequestDate?:           Date
    LastMediumTripRequestDate?:          Date
    LastShortHaulRequestDate?:           Date
    LastMediumHaulRequestDate?:          Date
    LastLongHaulRequestDate?:            Date
    UTCTimeOpenInHoursSinceMidnight?:    number
    UTCTimeCloseInHoursSinceMidnight?:   number
}
